# Generated by Django 3.0.5 on 2020-04-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20200414_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='Fab',
            new_name='Customer',
        ),
        migrations.AlterField(
            model_name='issues',
            name='date_closed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='date_created',
            field=models.DateField(null=True),
        ),
    ]
