# Generated by Django 3.0.5 on 2020-04-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20200414_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_closed',
            field=models.DateField(),
        ),
    ]
