# Generated by Django 3.0.5 on 2020-04-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20200414_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='date_closed',
        ),
    ]
