# Generated by Django 3.0.5 on 2020-04-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_remove_issue_date_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='Customer',
            new_name='Customer_name',
        ),
    ]
